### ISSUE TITLE
Re-implementer playback-modulen

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMplayback#10]

**Comment by Jimtrim** [comment]
Oppdatert slik at ting ser ut til å fungere i 1011c06359057a8d706d48f472c67dc151afaff2 , men må avvente til Plaback-server kan testes

**Comment by Jimtrim** [comment]
Opplasting og redigering fungerer.
Zip'ing ser ut til å fungere i form av filer opprettes på riktig lokasjon, men er utilgjengelige gjennom download.ukm.dev sin vhost
