### ISSUE TITLE
Blokker m4p-format

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMplayback#7]
Privat itunes-format

**Comment by Jimtrim** [comment]
Problematikk:

Det er brukt https://github.com/blueimp/jQuery-File-Upload/ i versjon 8.9.0.
Denne støtter ikke ProcessQueue, så det er ikke et valg.
Det kan hende det er mulig å bruke `change` og `drop`-eventene for å få filene ut av opplastings-køen, men jeg har ikke funnet noe objekt som lar med endre på opplastingskøen.

Pr nå kommer jeg ikke videre på denne, så issuet bør følges opp senere, og evt oppdatere jQuery-opplasteren.

**Comment by mariusmandal** [comment]
Lagt inn i playback-beskrivelse, og tas frem ved en større oppgradering av modulen
