### ISSUE TITLE
Fiks direktenedlasting av playback-filer

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMplayback#8]
De "fine" lenkene kræsjer på enkelte filer. Finn måte for å direkte-adressere filene

**Comment by mariusmandal** [comment]
redirect, kanskje?

**Comment by Jimtrim** [comment]
Manglet å få inn controller'en, så dette skal være ordnet.
Jeg greier ikke å teste videre på special-cases pga feil i Vagrant'en sitt vhost-oppsett for playback.ukm.dev

**Comment by mariusmandal** [comment]
Testes når playbackserveren er oppe igjen
